# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Knut Jackowski"
email: doxanthropos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sind persönliche Webseiten in den Zeiten von Twitter, Facebook und LinkedIn überflüssig geworden?
  Ich denke nicht, daher gibt es diese hier. Das ist meine. Wenn Du auch eine haben möchtest und nicht weißt wie, melde Dich einfach. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knutjackowski.de" # the base hostname & protocol for your site

# Social names
twitter_username: doxanthropos
github_username:  doxanthropos
linkedin_username: knutjackowski
codepen_username: doxanthropos

# commonly used assets
profile_picture: "/images/pensiveintheforest.jpg"

# Build settings
markdown: kramdown
